GRANT ALL PRIVILEGES ON DATABASE tictactoken TO tictactoken;
GRANT USAGE ON SCHEMA public TO tictactoken;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tictactoken;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tictactoken;